[package]
name = "jsonapi"
version = "0.1.0"
authors = ["Michiel Kalkman <michiel@nosuchtype.com>"]
description = "JSONAPI implementation"
documentation = "https://michiel.github.io/jsonapi-rust/jsonapi/index.html"
homepage = "https://github.com/michiel/jsonapi-rust"
repository = "https://github.com/michiel/jsonapi-rust.git"
readme = "https://github.com/michiel/jsonapi-rust/README.md"
keywords = ["jsonapi"]
categories = []
license = "MIT"

[dependencies]
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"

[badges]
travis-ci = { repository = "https://travis-ci.org/michiel/jsonapi-rust/", branch = "master" }
