[package]
name = "jsonapi"
version = "0.4.0"
authors = ["Michiel Kalkman <michiel@nosuchtype.com>"]
description = "JSONAPI implementation"
documentation = "https://docs.rs/jsonapi"
homepage = "https://github.com/michiel/jsonapi-rust"
repository = "https://github.com/michiel/jsonapi-rust.git"
readme = "README.md"
keywords = ["jsonapi"]
categories = []
license = "MIT"

[dependencies]
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
queryst = "1"
log = "0.3"

[dev-dependencies]
env_logger = "0.3"

[badges]
travis-ci = { repository = "https://travis-ci.org/michiel/jsonapi-rust/", branch = "master" }
